@extends('layouts.app')

@section('title', 'Export Center · TaskFlow')
@section('eyebrow', 'Workspace')
@section('page-title', 'Export Center')

@section('content')

    <div class="page-header">
        <h1>Export Center</h1>
        <p>Generate and download reports for projects, timesheets, and team workloads.</p>
    </div>

    <div class="grid-2">

        {{-- Create report form --}}
        <div class="card">
            <div class="section-header">
                <div>
                    <div class="section-title">Generate Report</div>
                    <div class="section-subtitle">Select parameters and export format</div>
                </div>
            </div>

            @if ($authUser->canExport())
                <form class="form-grid" action="{{ route('exports.store') }}" method="POST">
                    @csrf
                    <label>
                        <span class="label-text">Project</span>
                        <select name="project_id" required>
                            @foreach ($projects as $project)
                                <option value="{{ $project->id }}">{{ $project->name }}</option>
                            @endforeach
                        </select>
                    </label>
                    <label>
                        <span class="label-text">Report Type</span>
                        <select name="report_type" required>
                            <option value="task_list">Task List</option>
                            <option value="progress_summary">Project Progress Summary</option>
                            <option value="team_workload">Team Workload</option>
                        </select>
                    </label>
                    <label>
                        <span class="label-text">File Format</span>
                        <select name="format" required>
                            <option value="excel">Excel-compatible CSV</option>
                            <option value="pdf">PDF</option>
                        </select>
                    </label>
                    <div class="form-row">
                        <label>
                            <span class="label-text">Start Date</span>
                            <input type="date" name="start_date" value="{{ now()->startOfMonth()->toDateString() }}" required>
                        </label>
                        <label>
                            <span class="label-text">End Date</span>
                            <input type="date" name="end_date" value="{{ now()->toDateString() }}" required>
                        </label>
                    </div>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="shared_with_client" value="1">
                        <span>Share with client after generation</span>
                    </label>
                    <button class="btn btn-primary">
                        <svg width="13" height="13" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.8">
                            <path d="M11 7l-3 3-3-3M8 10V2"/>
                            <path d="M2 11v2a1 1 0 001 1h10a1 1 0 001-1v-2"/>
                        </svg>
                        Generate Report
                    </button>
                </form>
            @else
                <div class="empty-state">
                    You can view reports shared with your account from the list below.
                </div>
            @endif
        </div>

        {{-- Preview --}}
        <div class="card">
            <div class="section-header">
                <div>
                    <div class="section-title">Report Preview</div>
                    <div class="section-subtitle">{{ $previewExport?->preview_payload['title'] ?? 'No report selected' }}</div>
                </div>
                @if ($previewExport)
                    <a class="btn btn-primary btn-sm" href="{{ route('exports.download', $previewExport) }}">
                        <svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.8">
                            <path d="M11 7l-3 3-3-3M8 10V2"/>
                            <path d="M2 11v2a1 1 0 001 1h10a1 1 0 001-1v-2"/>
                        </svg>
                        Download
                    </a>
                @endif
            </div>

            @if ($previewExport)
                <div class="meta-grid" style="margin-bottom:16px;">
                    <div class="meta-item"><span>Project</span><strong>{{ $previewExport->project->name }}</strong></div>
                    <div class="meta-item"><span>Format</span><strong>{{ strtoupper($previewExport->format) }}</strong></div>
                    <div class="meta-item"><span>Generated by</span><strong>{{ $previewExport->requester->name }}</strong></div>
                    <div class="meta-item"><span>Shared with client</span><strong>{{ $previewExport->shared_with_client ? 'Yes' : 'No' }}</strong></div>
                </div>
                <div class="table-wrap">
                    <table>
                        <thead>
                            <tr>
                                @foreach ($previewExport->preview_payload['headers'] as $header)
                                    <th>{{ $header }}</th>
                                @endforeach
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($previewExport->preview_payload['rows'] as $row)
                                <tr>
                                    @foreach ($row as $cell)
                                        <td>{{ $cell }}</td>
                                    @endforeach
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @else
                <div class="empty-state">Select a report from the history below to preview it.</div>
            @endif
        </div>
    </div>

    {{-- Export history --}}
    <div class="card">
        <div class="section-header">
            <div>
                <div class="section-title">Export History</div>
                <div class="section-subtitle">Previously generated reports</div>
            </div>
        </div>
        <div class="table-wrap">
            <table>
                <thead>
                    <tr>
                        <th>Project</th>
                        <th>Type</th>
                        <th>Format</th>
                        <th>Requested By</th>
                        <th>Shared</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($exports as $export)
                        <tr>
                            <td>{{ $export->project->name }}</td>
                            <td>{{ strtoupper(str_replace('_', ' ', $export->report_type)) }}</td>
                            <td><span class="badge badge-default">{{ strtoupper($export->format) }}</span></td>
                            <td>{{ $export->requester->name }}</td>
                            <td>
                                @if ($export->shared_with_client)
                                    <span class="badge badge-green">Shared</span>
                                @else
                                    <span class="badge badge-default">Private</span>
                                @endif
                            </td>
                            <td>
                                <div style="display:flex;gap:8px;">
                                    <a href="{{ route('exports.index', ['preview' => $export->id]) }}" class="btn btn-ghost btn-sm">Preview</a>
                                    <a href="{{ route('exports.download', $export) }}" class="btn btn-secondary btn-sm">Download</a>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr><td colspan="6" class="empty-state">No reports have been generated yet.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

@endsection
